config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resource  :session, only: [:new, :create, :destroy]
  resources :questions do
    resources :answers
  end

  root to: 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates  :content, presence: true

  belongs_to :user
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates            :email, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ }
  before_validation    :downcase_email

  has_many :questions
  has_many :answers

  private
  def downcase_email
    email.downcase if email
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user_id = session[:user_id]
    @answer.save
    redirect_to question_path(@question)
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.update(:correct => params[:correct])
    @answer.save
    redirect_to question_path(@question)
  end

  def destroy
    @question. Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question)
  end

  private
  def answer_params
    params.require(:answer).permit(:content, :correct)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    # User.find(session[:user_id]) if session[:user_id]
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = session[:user_id]
    @question.save
    redirect_to questions_path
    # redirect_to question_path(@question)
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update(question_params)
    @question.save
    # redirect_to question_path(@question)
  end

  private
  def question_params
    params.require(:question).permit(:title, :content )
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # no special action, display new.html.erb
  # GET /login
  def new
  end

  # login a user: look up if exists, authenticate, add to session, redirect to back where they came from or redirect back to login after failed attempt
  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path        # aka sessions#new subject to change?
    else
      redirect_to new_session_path # back to login at sessions#new
    end
  end


  # logout a user: destroy a user! :D
  def destroy
    session[:user_id] = nil
    redirect_to questions_path
    # redirect_to new_session_path    # back to login sessions#new
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  @user = User.new
end

def create
  @user = User.new(user_params)

  if @user.save
    session[:user_id] = @user.id      #sign up and login too
    redirect_to root_path
  else
    render :new
  end
end

private
def user_params
  params.require(:user).permit(:email, :password, :password_confirmation)
end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Notstackoverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
  <%= link_to question.title, question_path(question)%>
<% end %>


<br>
<br>

<% if !session[:user_id] %>
  <%= link_to 'Log in', new_session_path %>
  <%= link_to 'Sign up', new_user_path %>
<% else %>
  <%= link_to 'New question', new_question_path %>
  <%= link_to 'Log out', session_path, method: :delete %>
<% end %>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>
  title : <%= f.text_field :title %>
  content : <%= f.text_field :content %>


  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<%= @question.title %>
<%= @question.content %>
<%= @question.user.email if @question.user%>

<h5> Add an answer </h5>
<%= form_for ([@question, @question.answers.new]), url: question_answers_path(@question), method: :post do |f| %>
<%= f.text_field :content %>
<%= f.submit %>
<% end %>

<h5> Answers </h5>
<% if @question.user.id == session[:user_id] %>
  <% @question.answers.each do |answer| %>
      <%= button_to "Mark as correct", url_for(controller: 'answers', action: 'update', :id => answer.id, question_id: @question.id), params: {:correct => "true"}, method: :put if answer.content %>
      <%= button_to "Unmark", url_for(controller: 'answers', action: 'update', :id => answer.id, question_id: @question.id), params: {:correct => "false"}, method: :put if answer.content %>
      <%= answer.content %>
      <%= answer.user.email if answer.user%>
  <% end %>

<% else %>
  <% @question.answers.each do |answer| %>
    <p>
    <%= answer.content %>
    <%= answer.user.email if answer.user %>
   </p>
  <% end %>

<% end %>

<%= link_to 'Back to index', questions_path %>

app/views/users/new.html.erb
<h1>Signup!</h1>

<% if @user.errors.any? %>
  <h2>Please correct the problems below before signing up.</h2>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for :user, url: users_path do |f| %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign me up" %>
<% end %>